[package]
name = "fbx-load"
version = "0.0.1"
authors = ["Takuma Yoshioka <nu11p0.6477@gmail.com>"]

[dependencies]
fbx-binary-reader = { git = "https://github.com/l1048576/fbx-binary-reader.git", tag = "ver-0.1.0" }
fnv = "^1.0"
log = "^0.3"
